### PR TITLE
Separate {% endexample %} tags from code blocks

### PR DESCRIPTION
**Pull request by ilyaspiridonov**
The closing {% endexample %} tags are currently placed on the same line as closing fenced code block tags (```). While Eleventy seems to render pages correctly, this still results in incorrect parsing of the markdown files by translation platforms (and by GitHub - see screenshot). 
This PR adds extra line breaks to separate the {% endexample %} tags from code blocks so we can correctly parse the files for translation.

Screenshot 2022-01-05 at 17 59 33

### CODE REVIEW

**Comment by ilyaspiridonov** [comment]
@patrickkettner FYI

**Review by sebastianbenz — CHANGES_REQUESTED** [review]
These docs are imported from the amphtml repo and the endexample tags are injected automatically. The line space needs to be added here: https://github.com/ampproject/bentojs.dev/blob/main/gulpfile.js/importDocs.js#L40

**Comment by ilyaspiridonov** [comment]
> These docs are imported from the amphtml repo and the endexample tags are injected automatically. The line space needs to be added here: https://github.com/ampproject/bentojs.dev/blob/main/gulpfile.js/importDocs.js#L40

@sebastianbenz Ah, got it, thanks! Added another commit to address that, PTAL.

**Review by sebastianbenz — APPROVED** [review]
Thanks!

**Pull request merged**
